services:
  db:
    image: postgres:14
    container_name: receivables-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: receivables
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase-migrate
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    depends_on:
      - db
    command: 
      --url=jdbc:postgresql://db:5432/receivables
      --username=postgres
      --password=postgres
      --driver=org.postgresql.Driver
      --changelog-file=changelog/master.yaml
      update

volumes:
  postgres-data: